import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { db } from "@/lib/prisma";
import crypto from 'crypto';

// Reusable transporter
const transporter = nodemailer.createTransport({
  host: "142.251.4.108", // Hardcoded Gmail SMTP IP to bypass DNS issues
  port: 587,
  secure: false, // Use STARTTLS
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
  tls: {
    servername: 'smtp.gmail.com', // Required for TLS verification when using IP
    rejectUnauthorized: false
  }
});

console.log("Transporter stabilized with IP bypass for user:", process.env.GMAIL_USER);

export async function POST(req) {
  try {
    const { disputeId, type } = await req.json();

    if (!disputeId) {
      return NextResponse.json({ error: "Dispute ID is required" }, { status: 400 });
    }

    console.log("Searching for dispute with ID:", disputeId);
    const dispute = await db.dispute.findUnique({
      where: { id: disputeId }
    });

    if (!dispute) {
      console.error("Dispute not found for ID:", disputeId);
      return NextResponse.json({ error: "Dispute not found" }, { status: 404 });
    }

    console.log("Dispute found:", dispute.category);

    if (!dispute.opponentEmail || !dispute.complainantEmail) {
      return NextResponse.json({ error: "Missing email addresses for parties" }, { status: 400 });
    }

    // TYPE 1: SEND LEGAL NOTICE
    if (type === "LEGAL_NOTICE") {
      const mailOptions = {
        from: `"Justifi Legal Assistant" <${process.env.GMAIL_USER}>`,
        to: dispute.opponentEmail,
        cc: dispute.complainantEmail, // Send copy to complainant
        subject: `⚠️ URGENT: Legal Notice Regarding Dispute - ${dispute.category}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #10b981;">
              <h2 style="color: #047857; margin: 0;">Formal Legal Notice</h2>
            </div>
            <div style="padding: 20px; background-color: #f8fafc; margin-top: 20px; border-radius: 8px;">
              <p><strong>To:</strong> ${dispute.opponentName}</p>
              <p><strong>From:</strong> ${dispute.complainantName}</p>
              <br/>
              <p>This is a formal legal notice generated by the Justifi AI Legal Assistant regarding a dispute categorized as <strong>${dispute.category}</strong>.</p>
              
              <div style="padding: 15px; background: white; border-left: 4px solid #10b981; margin: 20px 0; white-space: pre-wrap;">
                ${dispute.legalNotice}
              </div>

              <p>Please respond to this notice or join the mediation session that will be scheduled shortly to resolve this matter amicably.</p>
              
              <div style="margin-top: 30px; font-size: 12px; color: #64748b; text-align: center;">
                Generated securely by Justifi Legal App<br/>
                <a href="${process.env.NEXT_PUBLIC_BASE_URL}/dispute/${dispute.id}?role=opponent" style="color: #10b981;">View Dispute Dashboard</a>
              </div>
            </div>
          </div>
        `,
      };

      console.log("Attempting to send LEGAL_NOTICE email to:", dispute.opponentEmail);
      try {
        await transporter.verify();
        console.log("Transporter verification successful");
        await transporter.sendMail(mailOptions);
        console.log("Email sent successfully");
      } catch (err) {
        console.error("Nodemailer sendMail error:", err);
        throw err;
      }
      
      await db.dispute.update({
        where: { id: disputeId },
        data: { status: "NOTICE_SENT" }
      });

      return NextResponse.json({ success: true, message: "Legal notice sent" });
    }

    // TYPE 2: SEND MEDIATION INVITE (Google Meet link generator)
    if (type === "MEDIATION_INVITE") {
      // Generate a mock unique meet link (could be Jitsi or real GMeet if configured)
      const meetId = crypto.randomBytes(4).toString('hex') + '-' + crypto.randomBytes(4).toString('hex');
      const meetLink = `https://meet.jit.si/JustifiMediation-${meetId}`;
      
      const mailOptions = {
        from: `"Justifi Legal Assistant" <${process.env.GMAIL_USER}>`,
        to: [dispute.opponentEmail, dispute.complainantEmail], // Send to both
        subject: `📅 Scheduling Mediation: Dispute Resolution`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #3b82f6;">
              <h2 style="color: #2563eb; margin: 0;">Mediation Session Scheduled</h2>
            </div>
            <div style="padding: 20px; background-color: #f8fafc; margin-top: 20px; border-radius: 8px;">
              <p>Dear ${dispute.complainantName} and ${dispute.opponentName},</p>
              
              <p>A mediation video call has been generated to discuss and resolve the ongoing dispute amicably.</p>
              
              <div style="text-align: center; margin: 30px 0;">
                <a href="${meetLink}" style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                  Join Mediation Video Call
                </a>
                <p style="margin-top: 10px; font-size: 14px; color: #64748b;">Or copy link: ${meetLink}</p>
              </div>

              <div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 10px; margin-top: 20px;">
                <strong>Action Required:</strong> After the meeting, please visit your dispute dashboard to mark the case as resolved if an agreement is reached.
              </div>
              
              <div style="margin-top: 30px; font-size: 12px; color: #64748b; text-align: center;">
                Facilitated by Justifi AI Legal Assistant<br/>
                <a href="${process.env.NEXT_PUBLIC_BASE_URL}/dispute/${dispute.id}?role=opponent" style="color: #10b981;">View Dispute Dashboard</a>
              </div>
            </div>
          </div>
        `,
      };

      await transporter.sendMail(mailOptions);
      
      await db.dispute.update({
        where: { id: disputeId },
        data: { 
          status: "MEDIATION",
          meetLink 
        }
      });

      return NextResponse.json({ success: true, meetLink });
    }

    return NextResponse.json({ error: "Invalid email type" }, { status: 400 });

  } catch (error) {
    console.error("Email Error:", error);
    return NextResponse.json({ error: "Failed to send email: " + error.message }, { status: 500 });
  }
}
