import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { db } from "@/lib/prisma";
import crypto from 'crypto';

// Reusable transporter
const transporter = nodemailer.createTransport({
  host: "142.251.4.108", // Hardcoded Gmail SMTP IP to bypass DNS issues
  port: 587,
  secure: false, // Use STARTTLS
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
  tls: {
    servername: 'smtp.gmail.com', // Required for TLS verification when using IP
    rejectUnauthorized: false
  }
});

console.log("Transporter stabilized with IP bypass for user:", process.env.GMAIL_USER);

export async function POST(req) {
  try {
    const { disputeId, type } = await req.json();

    if (!disputeId) {
      return NextResponse.json({ error: "Dispute ID is required" }, { status: 400 });
    }

    console.log("Searching for dispute with ID:", disputeId);
    const dispute = await db.dispute.findUnique({
      where: { id: disputeId }
    });

    if (!dispute) {
      console.error("Dispute not found for ID:", disputeId);
      return NextResponse.json({ error: "Dispute not found" }, { status: 404 });
    }

    console.log("Dispute found:", dispute.category);

    if (!dispute.opponentEmail || !dispute.complainantEmail) {
      return NextResponse.json({ error: "Missing email addresses for parties" }, { status: 400 });
    }

    // TYPE 1: SEND LEGAL NOTICE
    if (type === "LEGAL_NOTICE") {
      const mailOptions = {
        from: `"Justifi Legal Assistant" <${process.env.GMAIL_USER}>`,
        to: dispute.opponentEmail,
        cc: dispute.complainantEmail, // Send copy to complainant
        subject: `⚠️ URGENT: Legal Notice Regarding Dispute - ${dispute.category}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #10b981;">
              <h2 style="color: #047857; margin: 0;">Formal Legal Notice</h2>
            </div>
            <div style="padding: 20px; background-color: #f8fafc; margin-top: 20px; border-radius: 8px;">
              <p><strong>To:</strong> ${dispute.opponentName}</p>
              <p><strong>From:</strong> ${dispute.complainantName}</p>
              <br/>
              <p>This is a formal legal notice generated by the Justifi AI Legal Assistant regarding a dispute categorized as <strong>${dispute.category}</strong>.</p>
              
              <div style="padding: 15px; background: white; border-left: 4px solid #10b981; margin: 20px 0; white-space: pre-wrap;">
                ${dispute.legalNotice}
              </div>

              <p>Please respond to this notice or join the mediation session that will be scheduled shortly to resolve this matter amicably.</p>
              
              <div style="margin-top: 30px; font-size: 12px; color: #64748b; text-align: center;">
                Generated securely by Justifi Legal App<br/>
                <a href="${process.env.NEXT_PUBLIC_BASE_URL}/dispute/${dispute.id}?role=opponent" style="color: #10b981;">View Dispute Dashboard</a>
              </div>
            </div>
          </div>
        `,
      };

      console.log("Attempting to send LEGAL_NOTICE email to:", dispute.opponentEmail);
      try {
        await transporter.verify();
        console.log("Transporter verification successful");
        await transporter.sendMail(mailOptions);
        console.log("Email sent successfully");
      } catch (err) {
        console.error("Nodemailer sendMail error:", err);
        throw err;
      }
      
      await db.dispute.update({
        where: { id: disputeId },
        data: { status: "NOTICE_SENT" }
      });

      return NextResponse.json({ success: true, message: "Legal notice sent" });
       // TYPE 2: SEND MEDIATION INVITE (Google Meet link generator)
    if (type === "MEDIATION_INVITE") {
      const { preferredDate, preferredTime } = await req.json();

      // Generate a mock unique meet link (could be Jitsi or real GMeet if configured)
      const meetId = crypto.randomBytes(4).toString('hex') + '-' + crypto.randomBytes(4).toString('hex');
      const meetLink = `https://meet.jit.si/JustifiMediation-${meetId}`;
      
      const sessionDate = preferredDate || dispute.preferredDate;
      const sessionTime = preferredTime || dispute.preferredTime;

      const mailOptions = {
        from: `"Justifi Legal Assistant" <${process.env.GMAIL_USER}>`,
        to: [dispute.opponentEmail, dispute.complainantEmail], // Send to both
        subject: `📅 Scheduled: Mediation Session for Dispute #${dispute.id.split('-')[0]}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #3b82f6;">
              <h2 style="color: #2563eb; margin: 0;">Mediation Session Scheduled</h2>
            </div>
            <div style="padding: 20px; background-color: #f8fafc; margin-top: 20px; border-radius: 8px;">
              <p>Dear ${dispute.complainantName} and ${dispute.opponentName},</p>
              
              <p>A mediation video call has been scheduled to discuss and resolve the ongoing dispute amicably.</p>
              
              <div style="background-color: white; padding: 15px; border-radius: 6px; border: 1px solid #e2e8f0; margin: 20px 0;">
                <p style="margin: 5px 0;"><strong>📅 Date:</strong> ${sessionDate ? new Date(sessionDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : 'To be confirmed'}</p>
                <p style="margin: 5px 0;"><strong>⏰ Time:</strong> ${sessionTime || 'To be confirmed'}</p>
                <p style="margin: 5px 0;"><strong>📂 Category:</strong> ${dispute.category}</p>
              </div>

              <div style="text-align: center; margin: 30px 0;">
                <a href="${meetLink}" style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                  Join Mediation Video Call
                </a>
                <p style="margin-top: 10px; font-size: 14px; color: #64748b;">Link: ${meetLink}</p>
              </div>

              <div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 10px; margin-top: 20px;">
                <strong>Note:</strong> Please be on time for the session. Your participation is recorded for the case file.
              </div>
              
              <div style="margin-top: 30px; font-size: 12px; color: #64748b; text-align: center;">
                Facilitated by Justifi AI Legal Assistant<br/>
                <a href="${process.env.NEXT_PUBLIC_BASE_URL}/dispute/${dispute.id}?role=opponent" style="color: #10b981;">View Dispute Dashboard</a>
              </div>
            </div>
          </div>
        `,
      };

      await transporter.sendMail(mailOptions);
      
      await db.dispute.update({
        where: { id: disputeId },
        data: { 
          status: "MEDIATION",
          meetLink,
          preferredDate: sessionDate ? new Date(sessionDate) : undefined,
          preferredTime: sessionTime
        }
      });

      return NextResponse.json({ success: true, meetLink });
    }

    }

    // TYPE 3: OPPONENT PENALTY WARNING
    if (type === "OPPONENT_PENALTY") {
      const { penaltyCount } = await req.json();
      let subject = "";
      let message = "";

      if (penaltyCount === 1) {
        subject = `⚠️ First Warning: Non-Responsiveness for Dispute #${dispute.id.split('-')[0]}`;
        message = `This is a formal warning regarding your non-responsiveness in the ongoing dispute for <strong>${dispute.category}</strong>. Your participation is required to resolve this matter.`;
      } else if (penaltyCount === 2) {
        subject = `🚨 FINAL WARNING: Impending Legal Escalation - Dispute #${dispute.id.split('-')[0]}`;
        message = `You have repeatedly failed to respond or join scheduled sessions. This is your <strong>FINAL WARNING</strong>. Failure to engage now will result in immediate escalation to senior legal counsel.`;
      } else {
        subject = `⚖️ LEGAL ESCALATION NOTICE: Dispute #${dispute.id.split('-')[0]}`;
        message = `Due to your continued absence and non-participation despite multiple warnings, this case has been <strong>OFFICIALLY ESCALATED</strong> to senior legal level for further action.`;
      }

      const mailOptions = {
        from: `"Justifi Legal Assistant" <${process.env.GMAIL_USER}>`,
        to: dispute.opponentEmail,
        cc: dispute.complainantEmail,
        subject,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid ${penaltyCount >= 2 ? '#ef4444' : '#f59e0b'};">
              <h2 style="color: ${penaltyCount >= 2 ? '#b91c1c' : '#b45309'}; margin: 0;">${penaltyCount === 3 ? 'Legal Escalation' : 'Penalty Warning'}</h2>
            </div>
            <div style="padding: 20px; background-color: #f8fafc; margin-top: 20px; border-radius: 8px;">
               <p><strong>To:</strong> ${dispute.opponentName}</p>
               <p><strong>Dispute ID:</strong> #${dispute.id.split('-')[0]}</p>
               <br/>
               <p style="font-size: 16px; line-height: 1.5;">${message}</p>
               
               <div style="margin-top: 30px; text-align: center;">
                 <a href="${process.env.NEXT_PUBLIC_BASE_URL}/dispute/${dispute.id}?role=opponent" style="background-color: ${penaltyCount >= 2 ? '#ef4444' : '#10b981'}; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                   Join Dispute Dashboard
                 </a>
               </div>

               <p style="margin-top: 20px; font-size: 13px; color: #64748b;">
                 Please note that consistent non-responsiveness is tracked as part of your legal record for this case.
               </p>
               
               <div style="margin-top: 30px; font-size: 11px; color: #94a3b8; text-align: center;">
                 Automated notification from Justifi AI<br/>
                 Property of Ansh Justifi-Tech
               </div>
            </div>
          </div>
        `,
      };

      await transporter.sendMail(mailOptions);
      return NextResponse.json({ success: true, message: "Penalty email sent" });
    }

    return NextResponse.json({ error: "Invalid email type" }, { status: 400 });

  } catch (error) {
    console.error("Email Error:", error);
    return NextResponse.json({ error: "Failed to send email: " + error.message }, { status: 500 });
  }
}
